azureOpenaiApiKey: ENC[AES256_GCM,data:eCmJY0iwg71z+MyQIIGsg6Jh14gOpYOtWJ3GRXtyEKB7ggiyLWrB5eXeNfwyuA7cA5oxeBK3LSlT191QaSP0ij4lIAOEqRuBE7/AQv6f/w8Omu11,iv:udsHpZey3iUC6WBA3+HUxfAPbbKftSLTMIr5HmgLhkE=,tag:TooQSoGhe+TO4/WxIzS/yg==,type:str]
langchainApiKey: ENC[AES256_GCM,data:tkvwTccOXQOH9hZyaoKUD+Aucn86JV+xTWZ4/dWLU6OWiMQZ6hsw/3NAzrUAu3vZSV5/,iv:DS5bp0tgfSfJlOkU3ZGd3AKn38dQMWWyJZ7r0GSNEwU=,tag:zjUWgHwxtJGo4fm7It/cHg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/production-02cb28ec/locations/us-east1/keyRings/helm/cryptoKeys/secrets
          created_at: "2022-07-20T12:13:26Z"
          enc: CiUA1AY8q6crHGW1r2KhTrN2mjaankPsoFhWsqkub2mF7ix1GZ6DEkkAXB0MM9qI4sBId8xzOYYtnEm9tSr+tE411JNCAyrZi6sW2sWNcwBn+eGkrtb1Xwds2ALDZL0H0K+CP0JameyUbAQvcjC0u7DW
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-26T14:56:20Z"
    mac: ENC[AES256_GCM,data:lU/8n5n47rgXbQWPGF51Z+i49c0asU1gzek8LOepLMGlssoUqcjCZdWWqJejdGsCO8nfq+S4QI8/vDPjV7UvPPrAwajZ71wGPEfXxku/6aM1gOY85TNfgfSDXlYJ+FDiu+/o8MlP3zFcxCrxbIeRKW7G2kW2mjynI6DhPSUOtt8=,iv:n2CRZTli39GUhiAeOTBCyaLDbOj/B9iqQTeh/Y1BOhM=,tag:Pt9yCXHRPV7C1GD3DNcUJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
