apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ include "microservice-genai-template.name" . }}
{{ include "microservice-genai-template.labels" . | indent 4 }}
stringData:
  SENTRY_DSN: {{ .Values.sentryDsnApi }}
  OAUTH2_CLIENT_SECRET: {{ .Values.oauth2ClientSecret }}
  AZURE_OPENAI_API_KEY: {{ .Values.azureOpenaiApiKey }}
  LANGCHAIN_API_KEY: {{ .Values.langchainApiKey }}
type: Opaque
