apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-genai-template.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "microservice-genai-template.name" . }}
{{ include "microservice-genai-template.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "microservice-genai-template.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
